version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - "16686:16686" # UI
      - "14268:14268" # collector

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
